### ISSUE TITLE
Step 4 – Upload a .zip file of each lambda function to Amazon S3

### ISSUE THREAD

**Issue by samhotnumb** [awslabs/lambda-refarch-mobilebackend#7]
Sorry, newbie ... Is this the S3 bucket created with Template One with logical id "S3mobileuseruploads"?

**Comment by waleoladehin** [comment]
No problem at all. I'd recommend have a separate bucket in your account for your lambda functions. For example, a bucket named:  'samhotnumb-lambda-mobilebackend'. It makes it easier to keep your functions in a separate S3 bucket than your uploaded image files or mobile user files since you'll normally configure different IAM policies for each use case. Let me know if that answers your question?

**Comment by samhotnumb** [comment]
That is easy enough. Sorry I did this with Eclipse prior to this example. 

Thank you.
